import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Octokit } from '@octokit/rest';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

@Injectable()
export class GithubService {
  private readonly logger = new Logger(GithubService.name);
  private octokit: Octokit;

  constructor(private readonly configService: ConfigService) {
    const token = this.configService.get<string>('GITHUB_API_TOKEN');
    this.octokit = new Octokit({ auth: token });
  }

  /**
   * Ensure a repository exists for this project. If it doesn't, create it.
   */
  async ensureRepository(repoName: string): Promise<{ owner: string, name: string, clone_url: string }> {
    try {
      const { data: user } = await this.octokit.rest.users.getAuthenticated();
      
      try {
        // Check if repo exists
        const { data: existingRepo } = await this.octokit.rest.repos.get({
          owner: user.login,
          repo: repoName,
        });
        this.logger.log(`Found existing GitHub repository: ${existingRepo.full_name}`);
        return { owner: user.login, name: existingRepo.name, clone_url: existingRepo.clone_url };
      } catch (error: any) {
        if (error.status === 404) {
          // Repo does not exist, create it
          this.logger.log(`Creating new GitHub repository: ${repoName}`);
          const { data: newRepo } = await this.octokit.rest.repos.createForAuthenticatedUser({
            name: repoName,
            description: `Generated by Contractor Website Builder`,
            private: true,
            auto_init: false,
          });
          return { owner: user.login, name: newRepo.name, clone_url: newRepo.clone_url };
        }
        throw error;
      }
    } catch (error) {
      this.logger.error(`Failed to ensure GitHub repository: ${error.message}`);
      throw error;
    }
  }

  /**
   * Commits the directory to the GitHub repository using local git CLI.
   */
  async commitAndPush(repoName: string, directory: string): Promise<void> {
    const token = this.configService.get<string>('GITHUB_API_TOKEN');
    if (!token) throw new Error('GITHUB_API_TOKEN is not configured');

    const { data: user } = await this.octokit.rest.users.getAuthenticated();
    const remoteUrl = `https://${user.login}:${token}@github.com/${user.login}/${repoName}.git`;

    try {
      this.logger.log(`Pushing code to GitHub for ${repoName}...`);
      
      // We are inside /tmp/builder-xxx
      // Need to init git, add remote, commit, and push
      await execAsync(`git init`, { cwd: directory });
      // Configure temp git user
      await execAsync(`git config user.name "AI Builder"`, { cwd: directory });
      await execAsync(`git config user.email "ai@builder.local"`, { cwd: directory });
      
      // Add and commit
      await execAsync(`git add .`, { cwd: directory });
      
      try {
          await execAsync(`git commit -m "feat: AI generated update"`, { cwd: directory });
      } catch (commitErr: any) {
          if (commitErr.message.includes('nothing to commit')) {
              this.logger.log(`No changes to commit for ${repoName}`);
              return;
          }
          throw commitErr;
      }
      
      // Force push to main
      await execAsync(`git branch -M main`, { cwd: directory });
      await execAsync(`git remote add origin ${remoteUrl}`, { cwd: directory }).catch(() => {
          // If remote already exists
          return execAsync(`git remote set-url origin ${remoteUrl}`, { cwd: directory });
      });
      await execAsync(`git push -u origin main --force`, { cwd: directory });
      
      this.logger.log(`Successfully pushed to GitHub repository ${repoName}`);
    } catch (error: any) {
      this.logger.error(`Failed to push to GitHub: ${error.message}`);
      throw error;
    }
  }
}
