import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Octokit } from '@octokit/rest';
import { InjectQueue } from '@nestjs/bullmq';
import { Queue } from 'bullmq';
import { QUEUE_NAMES } from '../common/constants/queue-names.constant';

@Injectable()
export class GithubService {
  private readonly logger = new Logger(GithubService.name);
  private octokit: Octokit;

  constructor(
    private readonly configService: ConfigService,
    @InjectQueue(QUEUE_NAMES.GITHUB_SYNC) private readonly githubSyncQueue: Queue
  ) {
    const token = this.configService.get<string>('GITHUB_API_TOKEN');
    this.octokit = new Octokit({ auth: token });
  }

  /**
   * Get the authenticated GitHub user.
   */
  async getAuthenticatedUser(): Promise<any> {
    const { data: user } = await this.octokit.rest.users.getAuthenticated();
    return user;
  }

  /**
   * Ensure a repository exists for this project. If it doesn't, create it.
   */
  async ensureRepository(repoName: string): Promise<{ owner: string, name: string, clone_url: string }> {
    try {
      const { data: user } = await this.octokit.rest.users.getAuthenticated();
      
      try {
        // Check if repo exists
        const { data: existingRepo } = await this.octokit.rest.repos.get({
          owner: user.login,
          repo: repoName,
        });
        this.logger.log(`Found existing GitHub repository: ${existingRepo.full_name}`);
        return { owner: user.login, name: existingRepo.name, clone_url: existingRepo.clone_url };
      } catch (error: any) {
        if (error.status === 404) {
          // Repo does not exist, create it
          this.logger.log(`Creating new GitHub repository: ${repoName}`);
          const { data: newRepo } = await this.octokit.rest.repos.createForAuthenticatedUser({
            name: repoName,
            description: `Generated by Contractor Website Builder`,
            private: true,
            auto_init: false,
          });
          return { owner: user.login, name: newRepo.name, clone_url: newRepo.clone_url };
        }
        throw error;
      }
    } catch (error) {
      this.logger.error(`Failed to ensure GitHub repository: ${error.message}`);
      throw error;
    }
  }

  /**
   * Enqueues a job to commit the directory to the GitHub repository using the background worker.
   */
  async commitAndPush(repoName: string, directory: string, projectId?: string, userId?: string, triggerDeployment?: boolean): Promise<void> {
    try {
      this.logger.log(`Queueing GitHub sync job for ${repoName}...`);
      
      await this.githubSyncQueue.add('sync', {
        projectId: projectId || 'unknown',
        userId: userId || 'unknown',
        repoName,
        directory,
        commitMessage: 'feat: AI generated update',
        triggerDeployment,
      }, {
        attempts: 3,
        backoff: { type: 'exponential', delay: 5000 }
      });
      
    } catch (error: any) {
      this.logger.error(`Failed to queue GitHub sync: ${error.message}`);
      throw error;
    }
  }
}
